version: '3'
services:
  notification-service:
    container_name: notification-service
    image: hicsail/notification-service
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../stack.env
volumes:
  mail-service: ~
