version: '3'
services:
  notification-service:
    container_name: notification-service
    image: hicsail/notification-service
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../stack.env
  mailserver:
    image: marcopas/docker-mailslurper
    container_name: mailserver
    ports:
      - 2500:2500
      - 8080:8080
      - 8085:8085
    restart: always
volumes:
  mail-service: ~
